pipeline {
    agent any

    stages {
        stage('Stage 1') {
            steps {
                bat '''javac DuplicateString.java
                java DuplicateString'''
                echo "File Executed Sucessfully"
            }
        }
    }
}
