version: '3.2'
services:
  client:
    build:
      context: ./client-app
    command: npm start
    depends_on:
      - server
    volumes:
      - ./client-app:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true

  server:
    build:
      context: ./Server
    command: npm run dev
    ports:
      - "5000:5000"
    volumes:
      - ./Server:/server
      - /server/node_modules
    environment:
      - WATCHPACK_POLLING=true



